apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  type: NodePort
  selector:
    app: todo-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      containers:
        - name: todo-service
          image: todo-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8002
          env:
            - name: DB_HOST
              configMapKeyRef:
                name: db-env-config
                key: DB_HOST
            - name: DB_PORT
              configMapKeyRef:
                name: db-env-config
                key: DB_PORT
            - name: DB_NAME
              configMapKeyRef:
                name: db-env-config
                key: DB_NAME
            - name: DB_USER
              secretKeyRef:
                name: db-env-secret
                key: SECRET_DB_USER
            - name: DB_PASSWORD
              secretKeyRef:
                name: db-env-secret
                key: SECRET_DB_PASSWORD