include:
  - docker-compose.base.yaml
services:
  auth_service:
    build:
      context: ./auth_service
    container_name: auth-container
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tododb
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      - db_service
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  todo_service:
    build:
      context: ./todo_service
    container_name: todo-container
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tododb
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      - db_service
    ports:
      - "8002:8002"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8002/health || exit 1" ]
      interval: 20s
      timeout: 5s
      retries: 2

networks:
  default:
    name: shared_net
    external: true
