include:
  - docker-compose.base.yaml
services:
  auth_service:
    build:
      context: ./auth_service
    container_name: auth-container
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tododb
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      - db
    ports:
      - "8000:8000"

  todo_service:
    build:
      context: ./todo_service
    container_name: todo-container
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tododb
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      - db
    ports:
      - "8002:8002"

networks:
  default:
    name: shared_net
    external: true
