services:
  db:
    image: postgres:15
    container_name: db-container
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: tododb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$DB_USER -d $$DB_NAME || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:


networks:
  default:
    name: shared_net
    external: true
