name: CI/CD Tests on Deploy

on:
  push:
    branches:
      - main
      - develop
      - feature/amir-canto/ci-cd-ga
  pull_request:
    branches:
      - main
      - develop
      - feature/amir-canto/ci-cd-ga

jobs:
  setup-os:
    name: OS Setup
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Install Dependencies
        run: |
          pip install -r src/auth_service/requirements.txt
          pip install -r src/todo_service/requirements.txt
          
      - name: Test Docker Installation
        run: |
          sudo systemctl enable docker
          sudo systemctl start docker
          docker version

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker

      - name: Pass Auth Environment Variables
        run: |
          echo "" > auth-service.env
          echo "SECRET_KEY=${{ secrets.AUTH_SERVICE_SECRET_KEY }}" >> src/auth_service/.env
          echo "ALGORITHM=${{ secrets.AUTH_SERVICE_ALGORITHM }}" >> src/auth_service/.env

      - name: Pass ToDo Environment Variables
        run: |
          echo "" > todo-service.env
          echo "SECRET_KEY=${{ secrets.TODO_SERVICE_SECRET_KEY }}" >> src/todo_service/.env
        
      - name: Run Application
        run: |
          chmod +x run_app.sh
          bash run_app.sh